version: '3.8'

services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    container_name: pelican-panel # Keeping a consistent container name
    restart: always
    networks:
      - default
    ports:
      # Default to port 80 for HTTP and 443 for HTTPS
      # Users can override these in the .env file if needed (e.g., for running behind another reverse proxy on the same host)
      - "${APP_PORT_HTTP:-80}:80"
      - "${APP_PORT_HTTPS:-443}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pelican-data:/pelican-data # Data persistence for Pelican Panel (includes SQLite DB, etc.)
      - pelican-logs:/var/www/html/storage/logs # Log persistence
      # Optional: Uncomment the line below to use a custom Caddyfile.
      # Create a Caddyfile in the same directory as this docker-compose.yml file.
      # - ./Caddyfile:/etc/caddy/Caddyfile 
    environment:
      XDG_DATA_HOME: /pelican-data # Specifies the base directory relative to which user-specific data files should be stored.
      APP_URL: "${APP_URL:-http://localhost}" # IMPORTANT: Set to your public URL (e.g., https://panel.example.com). Caddy uses this for SSL.
      ADMIN_EMAIL: "${ADMIN_EMAIL:-youremail@example.com}" # IMPORTANT: Used by Caddy for Let's Encrypt SSL certificate generation.
    labels:
      - "org.opencontainers.image.source=https://github.com/pelican-dev/panel"
      - "org.opencontainers.image.description=Pelican Panel, a game server management panel with an integrated Caddy web server."
      - "org.opencontainers.image.licenses=MIT"
      - "maintainer=GitHub Copilot"
      - "version=latest" # Corresponds to the image tag

volumes:
  pelican-data: # Stores panel data, including SQLite database, configuration, etc.
    driver: local
  pelican-logs: # Stores panel logs
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "${DOCKER_SUBNET:-172.20.0.0/16}" # Customizable subnet for the Docker network
